Add sale_order_invoicing_policy
qrtl/asx-custom pull request #23
Opened 2019-10-18 03:14 UTC by SokreamPhanqrl

This module allow user to change product's invoicing policy on sales order.

2019-10-18 06:00 UTC, TimLai125 requested changes
@SokreamPhanqrl Lets first discuss on these before you make any changes

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/__init__.py
> +from . import models
A few points to adjusts
1. From v11.0, `# -*- coding: utf-8 -*-` is not required anymore
2. Every file should end with an empty line
3. No need preceding empty lines for the import line

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/__manifest__.py
> +# -*- coding: utf-8 -*-
Remove this line

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/__manifest__.py
> +        "sale_stock",
Why this is `sale_stock`?

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/models/__init__.py
> +from . import sale_order
Same as the `sale_order_invoicing_policy/__init__.py`

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/models/sale_order.py
> +# -*- coding: utf-8 -*-
Remove this line

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/models/sale_order.py
> +import logging
Since logging is not being used in this file, please remove the related import. We want to keep things as clean as possible.

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/models/sale_order_line.py
> +# -*- coding: utf-8 -*-
Remove this line

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/models/sale_order_line.py
> +    # Ref: https://github.com/odoo/odoo/blob/43bf9ff29d1897405a575fa8643b7f80b5112c24/addons/sale/models/sale.py#L746-L759
This link looks not up-to-date, we want to give the link in v12.0

2019-10-18 06:00 UTC, TimLai125 commented on sale_order_invoicing_policy/models/sale_order_line.py
> +                if line.product_id.type == 'service':
Just a comment, do you know why we need `if` statement?

2019-10-21 01:48 UTC, yostashiro commented on sale_order_invoicing_policy/models/sale_order.py
> +    sale_order_invoice_policy = fields.Selection(
I'd prefer to make the field name just `invoice_policy` to be concise and be more consistent with style (product is `product_id` in all the models).

2019-10-21 03:50 UTC, yostashiro approved these changes

2019-10-21 04:11 UTC, merged