st2[1888][IMP]allow-empty-invoic-account_payment_related_invoice
qrtl/asx-custom pull request #86
Opened 2021-07-08 02:16 UTC by TomohiroAbe-Quartile

[1888](https://www.quartile.co/web#id=1888&action=771&model=project.task&view_type=form&menu_id=505)

2021-08-26 08:04 UTC, yostashiro requested changes

2021-08-26 08:04 UTC, yostashiro commented on account_view_adj_asx/views/account_payment_view.xml
> +                                groups="base.group_user"
```suggestion
```

2021-08-26 08:04 UTC, yostashiro commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="user_id" />
```suggestion
                            <field name="user_id" string="In Charge" />
```

2021-08-26 08:04 UTC, yostashiro commented on account_view_adj_asx/views/account_payment_view.xml
> +                        <tree string="Invoice" create="false">
```suggestion
                        <tree string="Invoices">
```

2021-08-26 08:04 UTC, yostashiro commented on account_view_adj_asx/README.rst
> +    :target: https://github.com/qrtl/asx-custom/tree/10.0/account_view_adj_asx
```suggestion
    :target: https://github.com/qrtl/asx-custom/tree/12.0/account_view_adj_asx
```

2021-08-26 08:04 UTC, yostashiro commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="number" />
```suggestion
                            <field name="number" />
                            <field name="name" />
```

2021-08-26 08:04 UTC, yostashiro commented on account_view_adj_asx/readme/DESCRIPTION.rst
> +- Adds treeview in account_invoice and account_payment view.
```suggestion
- Adjusts payment form and tree views to show related invoices.
```

2021-08-26 08:05 UTC, yostashiro commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="state" />
```suggestion
                            <field name="state" />
                            <field name="currency_id" invisible="1" />
```

2021-08-27 05:20 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="number" />
I added. Thank you.

2021-08-27 05:20 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="state" />
I added. Thank you.

2021-08-27 05:20 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/views/account_payment_view.xml
> +                                groups="base.group_user"
Deleted it.
Thank you.

2021-08-27 05:27 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/README.rst
> +    :target: https://github.com/qrtl/asx-custom/tree/10.0/account_view_adj_asx
Thank you, I re-generate readme.

2021-08-27 05:27 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="number" />
Thank you, I added.

2021-08-27 05:28 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/readme/DESCRIPTION.rst
> +- Adds treeview in account_invoice and account_payment view.
Thank you, I edited and re-generated Readme.

2021-08-27 05:28 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="state" />
Thank you, I added.

2021-08-27 05:28 UTC, TomohiroAbe-Quartile commented on account_view_adj_asx/views/account_payment_view.xml
> +                            <field name="user_id" />
Thank you, I added.

2021-08-27 09:57 UTC, yostashiro approved these changes
LGTM 👍

2021-08-30 00:50 UTC, merged